name: Actions

on:
  push:
    branches:
      - main

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - WebGL # WebGL.
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }} # Keep this if you have a Pro license, otherwise, you might try UNITY_SERIAL instead
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}     # Your Unity account email
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }} # Your Unity account password
        with:
          unityVersion: 6000.0.32f1             # Your Unity version
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Ask Butler to Send Package to itch
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }} # Your Itch.io API key
          CHANNEL: ${{ matrix.targetPlatform }}
          ITCH_GAME: 3knot3                  # Your Itch.io game name
          ITCH_USER: sarwar2arnob              # Your Itch.io username
          PACKAGE: ./build/${{ matrix.targetPlatform }}